### ISSUE TITLE
Can't get data for the tutorial

### ISSUE THREAD

**Issue by jiajie999** [brandon-rhodes/pycon-pandas-tutorial#1]
@brandon-rhodes   Great tutorial, thanks!

Problem:
When i run BUILD.sh the error happens, how can i get the imdbpy2sql.py?

```
/BUILD.sh: line 8: imdbpy2sql.py: command not found
chmod: *.csv: No such file or directory
rm: *.db: No such file or directory
```

**Comment by brandon-rhodes** [comment]
I will be cleaning that code up this week (it was written very quickly on a deadline in the week before I gave the tutorial!), but for now you can grab the ZIP file from the release that I did right before PyCon:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/releases

**Comment by jiajie999** [comment]
@brandon-rhodes  Thank you for the quick reply 

Orz
