### ISSUE TITLE
In README.md insutructions, switch to purely conda install ipython ..?

### ISSUE THREAD

**Issue by shaun10** [brandon-rhodes/pycon-pandas-tutorial#10]
Is it necessary to install ipython-notebook instead of just using ipython in the initial setup instructions? Was thinking maybe we could update readme to install ipython with notebook built-in.

**Comment by brandon-rhodes** [comment]
I am not sure what you mean by “ipython with notebook built-in” — at least with the way that Anaconda has the packages bundled, there are more dependencies beyond simply IPython that are necessary, I think, before you can open a notebook?

**Comment by shaun10** [comment]
I mean if you run:

```
conda install jupiter
```

You should get all iPython dependencies and the notebook right?

**Comment by shaun10** [comment]
This is regarding quick start section of README file btw

**Comment by brandon-rhodes** [comment]
I get this:

```
$ conda install jupiter
Fetching package metadata: ..
Error: No packages found in current linux-64 channels matching: jupiter
```

**Comment by shaun10** [comment]
Sorry Brandon, Autocorrect got the best of me! Here is the correct install I was thinking could be updated in README:

```
conda install jupyter
```

**Comment by brandon-rhodes** [comment]
Thanks for the pull request! It is now merged.
