### ISSUE TITLE
Error converting lists into csv files

### ISSUE THREAD

**Issue by jorwoods** [brandon-rhodes/pycon-pandas-tutorial#12]
Got the following output running build.py:

```
Reading "genres.list.gz" to find interesting movies
Found 216537 titles
Writing "titles.csv"
Finished writing "titles.csv"
Reading release dates from "release-dates.list.gz"
Finished writing "release_dates.csv"
Reading 'actors.list.gz'
Reading 'actresses.list.gz'
Traceback (most recent call last):
  File ".\BUILD.py", line 221, in <module>
    main()
  File ".\BUILD.py", line 132, in main
    if not_a_real_movie(fields[1]):
IndexError: list index out of range
```

**Comment by jorwoods** [comment]
Additional info: Python 3.4.3 :: Anaconda 2.3.0 (64-bit), running on windows.

**Comment by brandon-rhodes** [comment]
Drat — I wish I could reproduce it! The script runs without error for me:

```
Reading "genres.list.gz" to find interesting movies
Found 216537 titles
Writing "titles.csv"
Finished writing "titles.csv"
Reading release dates from "release-dates.list.gz"
Finished writing "release_dates.csv"
Reading 'actors.list.gz'
Reading 'actresses.list.gz'
Finished writing "cast.csv"
```

We need to see which line is giving you trouble. Could you add the following `if` statement to `BUILD.py` right above line 132 that was quoted in your exception?

```
            if len(fields) < 2:
                raise ValueError('broken line: {!r}'.format(line))
```

Let me know what it prints out — it should be the broken line that was somehow downloaded, and that we might be able to diagnose if we learn what it looks like. Thanks!

**Comment by jorwoods** [comment]
ValueError: broken line: b'Denoa" (1sC\xfce and Chloe\'s Bonda'

**Comment by jorwoods** [comment]
I tried to open the file in 7zip, and got an error stating bad CRC. Had to redownload 3 times to get a file that did not throw the error. Once that was downloaded, the build.py script works. It wasn't the script, but a corrupt file!

Thanks for helping to investigate anyway!

**Comment by brandon-rhodes** [comment]
No problem! I'm glad you were able to get a good copy of the file.
