### ISSUE TITLE
Solutions-1: "how many people have played ..." questions miss `.name.unique()`

### ISSUE THREAD

**Issue by AvverbioPronome** [brandon-rhodes/pycon-pandas-tutorial#15]
The answer in the solution counts how many movies with a character with that name there are in our `cast` dataframe, not how many actors have played a character: if an actor plays the same character in two different movies, they should be counted once, not twice.

The answer should be:

``` python
len(cast[cast.character == "Ophelia"].name.unique())
# gives 100
```

instead of 

``` python
c = cast
c = c[c.character == 'Ophelia']
len(c)
# gives 102
```

It only impacts Ophelia and The Stranger, as far as I see. (And Sidney Poitier and Judi Dench in the following questions about their roles, if by role we mean character [I don't know if we should].)

**Comment by brandon-rhodes** [comment]
I had a few minutes this evening, finally, to take a look, and I have added your solution to the Solutions-1 notebook. Thank you for this contribution!
