### ISSUE TITLE
BUILD.py file doesn't work

### ISSUE THREAD

**Issue by WillBishop12** [brandon-rhodes/pycon-pandas-tutorial#16]
I tried to run the BUILD.py file and got this error:
![image](https://cloud.githubusercontent.com/assets/16128532/16174355/94509a08-356a-11e6-8bcb-15c50f0fc4f6.png)
Any idea why?

**Comment by brandon-rhodes** [comment]
The problem appears to be that you are running the `BUILD.py` script without first downloading the data files that it needs from the IMDB. If you will try out the "Detailed Instructions" part of the project README, then you will first download the files and then the script should run successfully:

https://github.com/brandon-rhodes/pycon-pandas-tutorial#detailed-instructions

Good luck! Let me know if you run into more obstacles.
