### ISSUE TITLE
cannot run BUILD.py

### ISSUE THREAD

**Issue by davidoh0905** [brandon-rhodes/pycon-pandas-tutorial#19]
![image](https://cloud.githubusercontent.com/assets/15934401/20857792/30dd8a6c-b8eb-11e6-8644-8718df4f1494.png)

Hi Brandon,

I am dying to start following your video. but I cannot run this file properly. this is the error message. please help!!

Thank you!

David

**Comment by ac3gam3r** [comment]
@davidoh0905 I was also facing the same problem. Please use the code from the attached file.
[BUILD.py.txt](https://github.com/brandon-rhodes/pycon-pandas-tutorial/files/633198/BUILD.py.txt)

**Comment by brandon-rhodes** [comment]
Thank you for answering this question, @ac3gam3r, while I was busy with other duties! I am going to close this issue, but please — either of you — feel free to ask in the future if you find any more problems.
