### ISSUE TITLE
On cheatsheet is rename command correct?

### ISSUE THREAD

**Issue by birdsarah** [brandon-rhodes/pycon-pandas-tutorial#2]
Line 99 - df.rename({'a': 'y', 'b': 'z'})

I'm wondering whether it should be df.rename(columns={'a': 'y', 'b': 'z'}). 

At the least, this was the pattern I needed to change my column names on pandas 0.16.0.

**Comment by brandon-rhodes** [comment]
Thank you, Sarah! :)
