### ISSUE TITLE
problem with BUILD.py running !!

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/pycon-pandas-tutorial#20]
Hi Brandon,
Thank you very much for your great lecture, I really dying to practice the codes but this strange error message keeps coming, please help!!!
Thanks,

```
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
C:\Users\Ahmed\AppData\Local\Temp\Rar$DIa0.595\BUILD.py in <module>()
    221 
    222 if __name__ == '__main__':
--> 223      main()

C:\Users\Ahmed\AppData\Local\Temp\Rar$DIa0.595\BUILD.py in main()
    116         assert b'----' in next(lines)
    117 
--> 118         for line in lines:
    119             if line.startswith(b'----------------------'):
    120                 break

C:\Users\Ahmed\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\gzip.pyc in readline(self, size)
    462         bufs = []
    463         while size != 0:
--> 464             c = self.read(readsize)
    465             i = c.find('\n')
    466 

C:\Users\Ahmed\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\gzip.pyc in read(self, size)
    266             try:
    267                 while size > self.extrasize:
--> 268                     self._read(readsize)
    269                     readsize = min(self.max_read_chunk, readsize * 2)
    270             except EOFError:

C:\Users\Ahmed\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\gzip.pyc in _read(self, size)
    313         if buf == "":
    314             uncompress = self.decompress.flush()
--> 315             self._read_eof()
    316             self._add_read_data( uncompress )
    317             raise EOFError, 'Reached EOF'

C:\Users\Ahmed\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\gzip.pyc in _read_eof(self)
    352         if crc32 != self.crc:
    353             raise IOError("CRC check failed %s != %s" % (hex(crc32),
--> 354                                                          hex(self.crc)))
    355         elif isize != (self.size & 0xffffffffL):
    356             raise IOError, "Incorrect length of data produced"

IOError: CRC check failed 0xad043ea0L != 0x8a9d3edL 
```

**Comment by brandon-rhodes** [comment]
My guess is that one of the large files is damaged — when I download big files over HTTP (which has no protection against corruption) instead of HTTPS (which will notice if a bit is flipped), I often get errors. I would try downloading the big files again and see if that helps.

Also, you could try opening and reading each file yourself to see which one is damaged:
```
import gzip
gzip.open('the_big_file.gz').read()
```
That should attempt to read the compressed file whose name you give it to the file's very end, telling you if it downloaded successfully or not!

**Comment by ahmedtawfik17** [comment]
Thanks for reply, 
I redownleded the files twice, but BUILD is still acting strangely,
On Spyder, it gives "TypeError: a bytes-like object is required, not 'str'" !!! Why Spyder always behaves like this???!!!!  
Anyway, On Canopy, it finishes reading and writing files with no errors, 
but when working on Jupiter:
after HTML to CSV transformation..
"titles = pd.DataFrame.from_csv('data/titles.csv', index_col=None)"
 it gives "IOError: File data/titles.csv does not exist"  

I'm really sorry to annoy you, but really working through your materials and exercises is really important for my study,
Grateful thanks,

**Comment by ghost** [comment]
thanks for your reply,
I have checked the file as you said and it works fine with  the "genres.list.gz" and "release-dates.list.gz", but not with the large ones the "actors.list.gz" and "actresses.list.gz" which either the system crashes or sends the error 
"    gzip.open('actresses.list.gz').read()
  File "C:\Python27\lib\gzip.py", line 261, in read
    self._read(readsize)
  File "C:\Python27\lib\gzip.py", line 320, in _read
    self._add_read_data( uncompress )
  File "C:\Python27\lib\gzip.py", line 338, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError "

....I redownloaded the files and I'm redownloading it again.. Is there something else I should do?
Sry for annoying you and thanks for help..

**Comment by brandon-rhodes** [comment]
No, I do not know of any other way to get a correct version of a big file than trying over and over until it finally matches the checksum. Unless you can find a program or utility designed for folks using high-bit-error-rate connections, that does something like download the file 3 times and then compare the differences to hopefully have 2 good blocks "outvote" 1 bad block?

**Comment by ghost** [comment]
I downloaded it through git on a larger drive than the system drive and thanks God, it worked..
Grateful thanks for the materials and all your efforts,

**Comment by brandon-rhodes** [comment]
I am glad that you were able to get it downloaded — I wish you good fortune as you now proceed through the tutorial, and I hope that things proceed smoothly!
