### ISSUE TITLE
Error when running BUILD.py

### ISSUE THREAD

**Issue by lucariel** [brandon-rhodes/pycon-pandas-tutorial#23]
Hi!

I'm having problems with this, I tried checking the other issues but it doesn't seem to be the same problem
![image](https://cloud.githubusercontent.com/assets/18529380/21567402/a3d4247c-ce8a-11e6-8dc4-50b3c486951d.png)

Thanks!

**Comment by brandon-rhodes** [comment]
I agree that this error is different! That error indicates that the first two bytes of the file are corrupted. To tell whether a file is a gzipped file or not, gzip looks at the first two bytes. They are called the "magic number" of a file:

https://en.wikipedia.org/wiki/Magic_number_(programming)#Format_indicator

It looks like the file it is trying to open is either corrupted, or that the wrong file is under that filename. Looking at the code, it may be that your `genres.list.gz` file is damaged — maybe try removing it and downloading again?

**Comment by maheshwickramarachchi** [comment]
hi Brandon,

I watched the pandas tutorial and trying to follow the tutorial. as per the instructions i tried to run the BUILD.py, but i get this error. Could u pls help me?
```
 NameError: global name '__file__' is not defined
NameErrorTraceback (most recent call last)
<ipython-input-17-a29aaee6b06e> in <module>()
    224 
    225 if __name__ == '__main__':
--> 226     main()
<ipython-input-17-a29aaee6b06e> in main()
     11 
     12 def main():
---> 13     os.chdir(os.path.dirname(os.path.abspath(__file__)))
     14     if not os.path.isdir('../data'):
     15         os.makedirs('../data')
NameError: global name '__file__' is not defined
>>> 
```

**Comment by brandon-rhodes** [comment]
@maheshwickramarachchi Wow, that is a confusing error message! The name `__file__` should always be defined in Python, I had thought. What version of Python are you using, and how are you invoking the command from your operating system command line?

**Comment by maheshwickramarachchi** [comment]
hi,

I ran the given code in yhat

i havent installed python in my computer and  also i m using anaconda.

Do i need to install python separately

regards.
Mahesh🙂

**Comment by brandon-rhodes** [comment]
If you have installed Anaconda, then I think it comes with Python? Or maybe you could type `conda install python` if it does not seem yet to have been installed?

**Comment by brandon-rhodes** [comment]
I am going to close this for now as I've not heard from you for a while, but feel free to comment again in the future if your issue is still unresolved!

**Comment by mlapides** [comment]
Hi Brandon - trying to go through your tutorial but got this error in trying to run BUILD.py. Any suggestions? Thanks so much!

Traceback (most recent call last):
  File "/Users/home/Repositories/pandas_training/pycon-pandas-tutorial/build/BUILD.py", line 233, in <module>
    main()
  File "/Users/home/Repositories/pandas_training/pycon-pandas-tutorial/build/BUILD.py", line 26, in main
    line = next(lines)
ValueError: readline of closed file

**Comment by brandon-rhodes** [comment]
No, alas, I'm not familiar with that error. You might want to do some web searches to learn the conditions under which it can occur on your operating system.

**Comment by mlapides** [comment]
Thanks so much for the quick response, Brandon. it turned out to be a bug in Python. Once I updated Python, the problem was resolved -https://github.com/python/cpython/issues/89638

**Comment by brandon-rhodes** [comment]
Wow, that was a complicated issue! Thanks very much for leaving a link here on this issue, in case other folks run into the same error in the future.
