### ISSUE TITLE
Names off in cast.csv

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/pycon-pandas-tutorial#25]
![build](https://cloud.githubusercontent.com/assets/25283550/22343484/8a56d7b4-e3f8-11e6-8a9c-e3200b989cee.PNG)
![data_frame](https://cloud.githubusercontent.com/assets/25283550/22343493/8fe624b4-e3f8-11e6-9a2a-7a1ee37567f5.PNG)

Not sure what I'm doing wrong here. The build seemed to go fine and I added the encoding tag, but the names are looking funky. If anyone has time to send me some advice, it would be much appreciated! Cheers!

**Comment by brandon-rhodes** [comment]
Happily, you are not doing anything wrong! There are actually actors with dollar signs in their name:

http://www.imdb.com/title/tt4622512/fullcredits?ref_=tt_cl_sm#cast

So you can go ahead and try the tutorial. Enjoy!

**Comment by ghost** [comment]
Wonderful! Love the tutorial so far--learning lots. Thank you!
