### ISSUE TITLE
error running python BUILD.py

### ISSUE THREAD

**Issue by dthboyd** [brandon-rhodes/pycon-pandas-tutorial#26]
python BUILD.py
Reading "genres.list.gz" to find interesting movies
Found 234315 titles
Writing "titles.csv"
Traceback (most recent call last):
  File "BUILD.py", line 224, in <module>
    main()
  File "BUILD.py", line 58, in main
    output.writerow(('title', 'year'))
TypeError: a bytes-like object is required, not 'str'

**Comment by webparameter** [comment]
Solved this issue,
https://github.com/brandon-rhodes/pycon-pandas-tutorial/pull/27

**Comment by brandon-rhodes** [comment]
Thanks — I merged the pull request! Let me know if you have any further problems.
