### ISSUE TITLE
FileNotFoundError: File b'data/titles.csv' does not exist

### ISSUE THREAD

**Issue by PatrickLittlefield** [brandon-rhodes/pycon-pandas-tutorial#32]
Brandon.  
First, Thank you! for creating this great lesson and video for our collective benefit.

I'm a newbie, so please assume little to no knowledge on my part.

I was able to get the first two cells to run without error (importing MPL and activating the CSS to make the dataframes more readable, but as soon as I do anything else, I start getting these long daunting error messages. (please see below for what I get when I attempt to run the third cell). 

I can't even go to the bottom, add a few extra cells and get the 'titles' df to reveal itself in the 'first20/last20' format.  When I go to the bottom, type 'titles' , hit <shift-enter>, I get the following error message:

NameError                                 Traceback (most recent call last)
<ipython-input-8-22c39c2d3a5d> in <module>()
----> 1 titles

NameError: name 'titles' is not defined

Could you please tell me what I've done wrong?  I would like to follow this lesson and practice the exercises.

Example of error message on third cell (referenced above):
---------------------------------------------------------------------------
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-e0ddc450ec2e> in <module>()
----> 1 titles = pd.DataFrame.from_csv('data/titles.csv', index_col=None, encoding = 'utf-8')
      2 titles.head()

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\core\frame.py in from_csv(cls, path, header, sep, index_col, parse_dates, encoding, tupleize_cols, infer_datetime_format)
   1259                           parse_dates=parse_dates, index_col=index_col,
   1260                           encoding=encoding, tupleize_cols=tupleize_cols,
-> 1261                           infer_datetime_format=infer_datetime_format)
   1262 
   1263     def to_sparse(self, fill_value=None, kind='block'):

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    653                     skip_blank_lines=skip_blank_lines)
    654 
--> 655         return _read(filepath_or_buffer, kwds)
    656 
    657     parser_f.__name__ = name

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    403 
    404     # Create the parser.
--> 405     parser = TextFileReader(filepath_or_buffer, **kwds)
    406 
    407     if chunksize or iterator:

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    760             self.options['has_index_names'] = kwds['has_index_names']
    761 
--> 762         self._make_engine(self.engine)
    763 
    764     def close(self):

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
    964     def _make_engine(self, engine='c'):
    965         if engine == 'c':
--> 966             self._engine = CParserWrapper(self.f, **self.options)
    967         else:
    968             if engine == 'python':

C:\Users\Patrick\Anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1580         kwds['allow_leading_cols'] = self.index_col is not False
   1581 
-> 1582         self._reader = parsers.TextReader(src, **kwds)
   1583 
   1584         # XXX

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__ (pandas\_libs\parsers.c:4209)()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source (pandas\_libs\parsers.c:8873)()

FileNotFoundError: File b'data/titles.csv' does not exist
```

**Comment by brandon-rhodes** [comment]
(I've put triple back-ticks around the exceptions in your comment to get them to format correctly)

Did you run the setup script defined in the README? Until you run that, there won't be any data files. The instructions are on the front page of the repository — look for them here:
https://github.com/brandon-rhodes/pycon-pandas-tutorial#quick-start

**Comment by PatrickLittlefield** [comment]
Brandon.

Thank you very much for getting back to me so quickly.
Uh, no.  I didn't run the script.  I'll have a look and see if I can sort
it out.

Thanks again,

Patrick

**Comment by wrathofquan** [comment]
Hi Brandon,

The links to the compressed IMDB files seem to be broken. Thanks and really looking forward to going through the materials!

**Comment by PatrickLittlefield** [comment]
Brandon,

I cannot download the IMDB data from either of the links provided.  Could you please check to see if they work on your end?  Truly sorry to be such a PITA.

Patrick

**Comment by manyachen** [comment]
Here is a link for the data:
https://drive.google.com/file/d/0B8pFCL63GbotWndoMnhBZWFQSTg/view?usp=sharing

Hope it helps

**Comment by brandon-rhodes** [comment]
Drat — it looks like they have removed the traditional FTP links for the data:

http://www.imdb.com/interfaces

@manyachen, thank you for the data files — they hopefully will help a few people here in the short term. But I suspect that Google Drive will not allow those to stay up forever if tutorial users started downloading them frequently, or if other users of the old IMDB links find this GitHub issue and start downloading hundreds of times a day from your Drive account? Assuming that it won't last forever, I'll see if I can find some alternative data source.
