### ISSUE TITLE
ftp data sites do not work

### ISSUE THREAD

**Issue by jjisnow** [brandon-rhodes/pycon-pandas-tutorial#34]
Hi, the data files do not successfully download from the ftp sites. Is there some trick or setting that helps this to happen?

**Comment by jjisnow** [comment]
fixed my own problem - anonymous ftp doesn't necessarily work, but, 
https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/aminet/misc/imdb/
hosts an archived version of the imdb database which can be used instead - the data isn't exactly the same as it's several years old, but it still works

**Comment by INASIC** [comment]
If anyone else is having a similar problem, I found that separately opening the following links in a web browser downloaded the datasets:

ftp://ftp.fu-berlin.de/pub/misc/movies/database/temporaryaccess/actors.list.gz
ftp://ftp.fu-berlin.de/pub/misc/movies/database/temporaryaccess/actresses.list.gz
ftp://ftp.fu-berlin.de/pub/misc/movies/database/temporaryaccess/genres.list.gz
ftp://ftp.fu-berlin.de/pub/misc/movies/database/temporaryaccess/release-dates.list.gz

These links were provided in the BUILD.sh file

**Comment by alexandermdolson** [comment]
How do I make the files from your link work for the exercises @jjisnow ?
Can't get it to work correctly....
