### ISSUE TITLE
Data not downloadable

### ISSUE THREAD

**Issue by tahirahmad2030** [brandon-rhodes/pycon-pandas-tutorial#38]
I can't find data at ftp://ftp.fu-berlin.de/pub/temporaryaccess/misc/movies/database/actors.list.gz
I think the data has been removed.
I also checked  http://www.imdb.com/interfaces.

**Comment by fernikalo** [comment]
Hi tahirahmad2030,
I had the same problem and navigating in the ftp server from fu-berlin.de I found the data in a different folder. It seems that they restructured the directory.
You can find the data now under following link:
 ftp://ftp.fu-berlin.de/misc/movies/database/frozendata/
I think the issue can be closed.
Regards
Fernando

**Comment by brandon-rhodes** [comment]
Thanks for letting me know about the new URLs!
