### ISSUE TITLE
Solutions-1.ipynb doesn't work

### ISSUE THREAD

**Issue by Hisham-Hussein** [brandon-rhodes/pycon-pandas-tutorial#39]
Hi brandon, and thanks for your wonderful tutorial. 

there seems to be an issue with solutions-1.ipynb .. it doesn't open and gives the following error:

"Error loading notebook
Unreadable Notebook: D:\Data Science\pandas-brendon\Solutions-1.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...',)"

the other notebooks work like a charm though. 

I noticed you made a recent commit to this specific recently. This could be the reason? 

Thanks again

**Comment by brandon-rhodes** [comment]
Thanks for letting me know — I think it's fixed now; simply re-open the issue if it's not!
