### ISSUE TITLE
‘’FTP‘’ protocol problem

### ISSUE THREAD

**Issue by DMU-XiongJun** [brandon-rhodes/pycon-pandas-tutorial#41]
Hello, can you provide a more feasible way to download data sets?thanks

**Comment by brandon-rhodes** [comment]
What is proving infeasible about FTP?

**Comment by DMU-XiongJun** [comment]
I use ‘My Computer’ to go to the ‘ftp’ URL, download the dataset, and then it jump to the IE browser download interface, but I can’t download the dataset correctly, so I don’t understand why the download failed. I am a college student from China, but I use vpn to go online and I also hope to teach.thanks!

**Comment by brandon-rhodes** [comment]
If your browser is not correctly fetching the file, maybe you could use a small Python script to fetch it? I just found this when I searched for how to use Python to download a file:

https://stackoverflow.com/questions/11768214/python-download-a-file-over-an-ftp-server

**Comment by brandon-rhodes** [comment]
(As I haven't heard back, I'm closing this issue for now to keep my dashboard clean, but if you have further problems with FTP that you'd like to discuss, feel free to reopen it!)
