### ISSUE TITLE
Exercise 2 - Plotting n values over career questions

### ISSUE THREAD

**Issue by banjum** [brandon-rhodes/pycon-pandas-tutorial#43]
```

# Plot the n-values of the roles that Judi Dench has played over her career.
c = cast
c = c[c.name == 'Judi Dench'].sort_values('year')
c = c[c.n.notnull()]
c.plot(x='year', y='n', kind='scatter')
```

As far as plotting is concerned, do we really need sort_values() and notnull() here? Null values are ignored in plotting and the x series is automatically sorted as per my understanding. We can keep these solutions, but having a comment to the effect will add clarity.

**Comment by brandon-rhodes** [comment]
Thank you!
