### ISSUE TITLE
Handling UTF-8 Encoding for cast.csv

### ISSUE THREAD

**Issue by elico5** [brandon-rhodes/pycon-pandas-tutorial#44]
Hello,

I'm just getting starting working through the exercises after watching the PyCon talk on YouTube. I'm having trouble reading in the 'cast.csv' file. In particular, I can see that the names with accented characters confuse my dataframe, and come up as question marks. See below:

<img width="1140" alt="screen shot 2019-01-10 at 12 30 39 pm" src="https://user-images.githubusercontent.com/43277513/50985991-a1fedc00-14d3-11e9-86bd-44021e0ba42e.png">

In the above screenshot I try to read in the csv by adding encoding = 'utf-8' to the .read_csv function's parameters. Clearly this is not working, but I have been unable to implement the fix on my own after searching the web for almost an hour; I should note the first thing I tried was using the commands detailed on the cheat sheet (import sys; reload(sys); sys.setdefaultencoding('utf-8')), but these don't seem to be compatible in python3 and internet communities say to avoid this set of commands.

I would appreciate any help on this issue - looking to continue working on the exercises. Thanks!

**Comment by elico5** [comment]
> I would appreciate any help on this issue - looking to continue working on the exercises. Thanks!

Should note that I'm actually not having trouble with the exercises - though I am still curious on how one would resolve the issue presented above

**Comment by brandon-rhodes** [comment]
As a first step, try reading the import code that creates the CSV, in case the question marks were deliberate — I might have added them myself manually, because of not being able to get Python under Windows to ever behave consistently for folks under Python 2?

**Comment by brandon-rhodes** [comment]
I found it! The question marks were my way of making things ASCII so they'd work on Windows:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/blob/master/build/BUILD.py#L222

Do you have a suggestion of what might be a better approach instead? I'm open to ideas!

**Comment by brandon-rhodes** [comment]
I'm going to close this for now, but if someone who knows more than I do about the behavior of Python under Windows in this circumstance would like to weigh in, I'll be open to a better way of handling non-ASCII characters here. Thanks for the report, simply press "Reopen" if more information becomes available!
