### ISSUE TITLE
please help me with the build.py issue

### ISSUE THREAD

**Issue by haribez** [brandon-rhodes/pycon-pandas-tutorial#45]
= RESTART: /Users/haribezaldein/pycon-pandas-tutorial-master/build/BUILD.py =
Traceback (most recent call last):
  File "/Users/haribezaldein/pycon-pandas-tutorial-master/build/BUILD.py", line 226, in <module>
    main()
  File "/Users/haribezaldein/pycon-pandas-tutorial-master/build/BUILD.py", line 22, in main
    lines = iter(gzip.open('genres.list.gz'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'genres.list.gz'

**Comment by brandon-rhodes** [comment]
Could you share the command you are running? It looks like you might be running the Python script without running the shell script first — the README shows how to run the shell script:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/blob/master/README.md

If you saw instructions that led you to run the `.py` file before the `.sh` file, I will fix those instructions — let me know what you were trying to run, please! Thanks.

**Comment by haribez** [comment]
I really appreciate your help. I was able to run it using the Mac Terminal. I basically inputted the shell script and it worked perfectly. The only thing is that people should use cd pycon-pandas-tutorial-master if they download the file instead of cd pycon-pandas-tutorial. 

Thank you for your individualized attention and the contribution you make to our field!

**Comment by brandon-rhodes** [comment]
I'm glad you got it working! Good luck as you continue learning Pandas.
