### ISSUE TITLE
genres.list.gz is not parsed by BUILD.py

### ISSUE THREAD

**Issue by ReddyKilowatt** [brandon-rhodes/pycon-pandas-tutorial#46]
When running BUILD.py with all 4 data files in the build directory, I've noticed that only 3 csv files are generated under /data
cast.csv
release_dates.csv
titles.csv

Looking at BUILD.py, genres.csv is never written. No error message is displayed.

See the attached screenshot showing BUILD.py running,

![no_genres](https://user-images.githubusercontent.com/9022863/52439010-6c97df00-2acf-11e9-888d-2f61004314c7.jpg)

**Comment by brandon-rhodes** [comment]
That's correct! The build file reads genres but does not write them out. They are only used to filter the selection of movies included in the main dataset.

**Comment by brandon-rhodes** [comment]
So — before we close out this issue: is there any way the script could have set better expectations so the lack of an output file would have been expected rather than surprising? If so then we can adjust the messaging to compensate!

**Comment by ReddyKilowatt** [comment]
No, I don’t think so.
