### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by buenosjumper** [brandon-rhodes/pycon-pandas-tutorial#6]
where are the titles.csv and cast.csv data files.

**Comment by brandon-rhodes** [comment]
Could you paste the errors that you are getting, so that I can see which line of code is triggering the error? Thanks!

**Comment by buenosjumper** [comment]
Hi Brandon,

Thanks for getting back to me. I assumed the titles.csv and cast.csv files
would be in the .zip file, but they are not.

Here's the error:

Thanks again! Peter

```
titles = pd.DataFrame.from_csv('data/titles.csv', index_col=None,
encoding ='utf-8')

titles.head()
```

```
IOError
                                  Traceback (most recent call
last)<ipython-input-4-dbda21885b5d> in <module>()----> 1 titles =
pd.DataFrame.from_csv('data/titles.csv', index_col=None, encoding
='utf-8')      2 titles.head()
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc
in from_csv(cls, path, header, sep, index_col, parse_dates, encoding,
tupleize_cols, infer_datetime_format)   1036
parse_dates=parse_dates, index_col=index_col,   1037
        encoding=encoding, tupleize_cols=tupleize_cols,-> 1038
                  infer_datetime_format=infer_datetime_format)   1039
  1040     def to_sparse(self, fill_value=None, kind='block'):
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc
in parser_f(filepath_or_buffer, sep, dialect, compression,
doublequote, escapechar, quotechar, quoting, skipinitialspace,
lineterminator, header, index_col, names, prefix, skiprows,
skipfooter, skip_footer, na_values, na_fvalues, true_values,
false_values, delimiter, converters, dtype, usecols, engine,
delim_whitespace, as_recarray, na_filter, compact_ints, use_unsigned,
low_memory, buffer_lines, warn_bad_lines, error_bad_lines,
keep_default_na, thousands, comment, decimal, parse_dates,
keep_date_col, dayfirst, date_parser, memory_map, float_precision,
nrows, iterator, chunksize, verbose, encoding, squeeze,
mangle_dupe_cols, tupleize_cols, infer_datetime_format,
skip_blank_lines)    472
skip_blank_lines=skip_blank_lines)    473 --> 474         return
_read(filepath_or_buffer, kwds)    475     476     parser_f.__name__ =
name
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc
in _read(filepath_or_buffer, kwds)    248     249     # Create the
parser.--> 250     parser = TextFileReader(filepath_or_buffer, **kwds)
   251     252     if (nrows is not None) and (chunksize is not None):
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc
in __init__(self, f, engine, **kwds)    564
self.options['has_index_names'] = kwds['has_index_names']    565 -->
566         self._make_engine(self.engine)    567     568     def
_get_options_with_defaults(self, engine):
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc
in _make_engine(self, engine)    703     def _make_engine(self,
engine='c'):    704         if engine == 'c':--> 705
self._engine = CParserWrapper(self.f, **self.options)    706
else:    707             if engine == 'python':
/Users/beccapeter/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc
in __init__(self, src, **kwds)   1070
kwds['allow_leading_cols'] = self.index_col is not False   1071 ->
1072         self._reader = _parser.TextReader(src, **kwds)   1073
1074         # XXX
pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3173)()
pandas/parser.pyx in pandas.parser.TextReader._setup_parser_source
(pandas/parser.c:5912)()
IOError: File data/titles.csv does not exist
```

**Comment by brandon-rhodes** [comment]
Currently, the files need to be downloaded manually — check out the README file for instructions! But using this traceback that you have added in, I will see if I can make download automatic for people who just start at the top of the notebook and try running it!

**Comment by parul8ue** [comment]
BUILD.py is missing in the .zip file as well!

**Comment by brandon-rhodes** [comment]
It is a little hard to find — you should find it inside of the `build` directory, where all of the build tools are grouped together.

**Comment by parul8ue** [comment]
It is there in the build directory in the master branch, but missing in the .zip file!

**Comment by brandon-rhodes** [comment]
Which download mechanism are you using? I just pressed “Download ZIP” that is over on the right side of the main project page, below the git URL for the project, and the `.zip` file that was downloaded to my hard drive does have a `build/BUILD.sh` file. Here is the full file listing:

```
$ unzip -l pycon-pandas-tutorial-master.zip                        ~/Downloads 
Archive:  pycon-pandas-tutorial-master.zip
171f9bfa1aae69fd680047aa6fe1576b75b3d8e8
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-07-13 23:15   pycon-pandas-tutorial-master/
      120  2015-07-13 23:15   pycon-pandas-tutorial-master/.gitignore
   318883  2015-07-13 23:15   pycon-pandas-tutorial-master/All.ipynb
    25484  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-1.ipynb
    19211  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-2.ipynb
    13100  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-3.ipynb
    13861  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-4.ipynb
    13794  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-5.ipynb
    16052  2015-07-13 23:15   pycon-pandas-tutorial-master/Exercises-6.ipynb
     1094  2015-07-13 23:15   pycon-pandas-tutorial-master/LICENSE.txt
     2876  2015-07-13 23:15   pycon-pandas-tutorial-master/README.md
    51284  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-1.ipynb
   105121  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-2.ipynb
    38645  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-3.ipynb
   128562  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-4.ipynb
    62822  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-5.ipynb
    30366  2015-07-13 23:15   pycon-pandas-tutorial-master/Solutions-6.ipynb
        0  2015-07-13 23:15   pycon-pandas-tutorial-master/build/
     6072  2015-07-13 23:15   pycon-pandas-tutorial-master/build/BUILD.py
      372  2015-07-13 23:15   pycon-pandas-tutorial-master/build/BUILD.sh
     2162  2015-07-13 23:15   pycon-pandas-tutorial-master/build/split.py
     5187  2015-07-13 23:15   pycon-pandas-tutorial-master/cheat-sheet.txt
        0  2015-07-13 23:15   pycon-pandas-tutorial-master/images/
    92828  2015-07-13 23:15   pycon-pandas-tutorial-master/images/Diagrams.ipynb
      325  2015-07-13 23:15   pycon-pandas-tutorial-master/images/Makefile
       54  2015-07-13 23:15   pycon-pandas-tutorial-master/images/loop.sh
      207  2015-07-13 23:15   pycon-pandas-tutorial-master/images/sample.csv
      679  2015-07-13 23:15   pycon-pandas-tutorial-master/images/tmp.dot
       79  2015-07-13 23:15   pycon-pandas-tutorial-master/requirements.sh
      225  2015-07-13 23:15   pycon-pandas-tutorial-master/sales1.csv
      615  2015-07-13 23:15   pycon-pandas-tutorial-master/sales2.csv
     4221  2015-07-13 23:15   pycon-pandas-tutorial-master/script.txt
       74  2015-07-13 23:15   pycon-pandas-tutorial-master/style-notebook.css
      597  2015-07-13 23:15   pycon-pandas-tutorial-master/style-table.css
---------                     -------
   954972                     34 files
```

Could you share the listing from the ZIP file that you are receiving, so that we can compare and figure out what is missing? Thank you!

**Comment by parul8ue** [comment]
Weird! I just clicked on the .zip on the releases page
https://github.com/brandon-rhodes/pycon-pandas-tutorial/releases/, and
unzipped. Listing below, and it doesn't include build.py. A couple other
people at work tried and ran into the same issue.

Paruls-MacBook-Pro:Downloads parulgupta$ unzip
pycon-pandas-tutorial-1.0.zip

Archive:  pycon-pandas-tutorial-1.0.zip

cd7d1d91dd26681082a5752c23a55e9fe7cbf9d2

   creating: pycon-pandas-tutorial-1.0/

  inflating: pycon-pandas-tutorial-1.0/.gitignore

  inflating: pycon-pandas-tutorial-1.0/All.ipynb

  inflating: pycon-pandas-tutorial-1.0/Diagrams.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-1.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-2.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-3.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-4.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-5.ipynb

  inflating: pycon-pandas-tutorial-1.0/Exercises-6.ipynb

  inflating: pycon-pandas-tutorial-1.0/Makefile

  inflating: pycon-pandas-tutorial-1.0/Solutions-1.ipynb

  inflating: pycon-pandas-tutorial-1.0/Solutions-2.ipynb

  inflating: pycon-pandas-tutorial-1.0/Solutions-3.ipynb

  inflating: pycon-pandas-tutorial-1.0/Solutions-4.ipynb

  inflating: pycon-pandas-tutorial-1.0/Solutions-5.ipynb

  inflating: pycon-pandas-tutorial-1.0/Solutions-6.ipynb

   creating: pycon-pandas-tutorial-1.0/build/

  inflating: pycon-pandas-tutorial-1.0/build/BUILD.sh

  inflating: pycon-pandas-tutorial-1.0/build/Reduce.ipynb

 extracting: pycon-pandas-tutorial-1.0/build/requirements.txt

  inflating: pycon-pandas-tutorial-1.0/build/split.py

  inflating: pycon-pandas-tutorial-1.0/cheat-sheet.txt

 extracting: pycon-pandas-tutorial-1.0/loop.sh

  inflating: pycon-pandas-tutorial-1.0/problems.txt

  inflating: pycon-pandas-tutorial-1.0/requirements.sh

  inflating: pycon-pandas-tutorial-1.0/sales1.csv

  inflating: pycon-pandas-tutorial-1.0/sales2.csv

  inflating: pycon-pandas-tutorial-1.0/sample.csv

  inflating: pycon-pandas-tutorial-1.0/script.txt

  inflating: pycon-pandas-tutorial-1.0/style-notebook.css

  inflating: pycon-pandas-tutorial-1.0/style-table.css

  inflating: pycon-pandas-tutorial-1.0/tmp.dot

  inflating: pycon-pandas-tutorial-1.0/todo.txt

SlideRule http://mysliderule.com/: Learn something new

**Comment by brandon-rhodes** [comment]
In your listing, I see it listed as:

```
pycon-pandas-tutorial-1.0/build/BUILD.sh
```

Its name is in all capital letters to make the name bigger and more obvious and, the tradition says, easier for people to see and find. Does the fact that its name is in capital letters in fact make it harder for you to find in the listing and on your disk? If so, then I could try switching it to lower-case letters — what do you think?

**Comment by parul8ue** [comment]
Did notice the BUILD.sh file, and the case wasn't a problem . The confusion
was because of the instructions that mention the build.py :)

SlideRule http://mysliderule.com/: Learn something new

**Comment by brandon-rhodes** [comment]
Thank you for your patience! For a moment I got mixed up about which file we were searching for.

I see the problem now: you are pulling the ZIP file from the Releases page, which gives you the tutorial as it existed back in April, but you are trying to use it with the instructions in the current README, which is more recent.

Now that the PyCon conference is over, there is no reason for having a release any more — it will only encourage people to download out-of-date code as I continue to make fixes to the tutorial — so I have deleted it. The download button that will get you an up-to-date version of the tutorial is the “Download ZIP” button over in the right margin of the front page:

https://github.com/brandon-rhodes/pycon-pandas-tutorial

If you use that download button, then you should get an up-to-date copy of the tutorial, whose contents will match the current README. Let me know whether it works!

**Comment by parul8ue** [comment]
all good now, thanks so much!

SlideRule http://mysliderule.com/: Learn something new

**Comment by brandon-rhodes** [comment]
I'm glad that resolved your issue! Let me know if you have any more problems. :)
