### ISSUE TITLE
Be more specific with English in questions

### ISSUE THREAD

**Issue by cboyda** [brandon-rhodes/pycon-pandas-tutorial#60]
For example, the question 'How many movies have the title "Hamlet"?'
If you assume this means title EXACTLY equal to "Hamlet" you get
(titles['title'] == 'Hamlet').sum() RETURNS 18
but 
this could also mean, any movies with the word Hamlet in its title, which is more complicated as
(titles['title'].str.contains('Hamlet', case=False)).sum() RETURNS 54

**Comment by brandon-rhodes** [comment]
The question has generally not caused confusion in the past, but I've updated it to tighten the language a bit. Hopefully that prevents any ambiguity!
