### ISSUE TITLE
I found some strange characters in the cast.csv. Is this normal?

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/pycon-pandas-tutorial#7]
<img width="821" alt="screen shot 2015-08-25 at 10 26 49 pm" src="https://cloud.githubusercontent.com/assets/700550/9466468/6d3744ee-4b78-11e5-9a0e-7bffb34460d4.png">
See the name column. Not sure if this is correct or not.

**Comment by brandon-rhodes** [comment]
Those characters are normal — the dollar sign is a valid character in an actor name. Too $hort, for example, is a rapper:

https://en.wikipedia.org/wiki/Too_Short

Could you give an example of an exercise that is not working?

**Comment by ghost** [comment]
I was wrong. 
I have removed the "Certainly, lots of exercises don't work". 
I didn't read the questions probably.

Thanks for the explain. That's the culture difference I guess.

**Comment by brandon-rhodes** [comment]
No problem. Enjoy your foray into the strange world that is Hollywood and stage names!
