### ISSUE TITLE
Error converting to csv files 

### ISSUE THREAD

**Issue by Milja88** [brandon-rhodes/pycon-pandas-tutorial#9]
Hello,

I keep getting this error when I try to convert the data in the build file into csv files:

```
 File "Build.py", line 217
    return s.decode<"ascii", "replace">.replace<u'\ufffd', u'?'>
SyntaxError: invalid syntax
```

I have tried deleting all of the zip files for the course and re-downloading them, starting from scratch. My friend was able to get everything working on his computer without issue and so we cannot figure out what the problem is. Can you offer any advice or fixes? 

Thank you!

**Comment by brandon-rhodes** [comment]
It looks like something is damaging that file, by replacing parentheses with angle brackets. Here is what that line really looks like:

```
return s.decode('ascii', 'replace').replace(u'\ufffd', u'?')
```

There must be some step where instead of being pulled out of the zip file intact, the copy of the file on your computer is getting altered.

**Comment by Milja88** [comment]
Thank you so much for replying so quickly. I went back and looked into the code and found that I made an error in reading what the error given stated. The code is not being altered, I just mistook the ( ) signs for < > signs. The code is written correctly in the file. However, I am still getting the same SyntaxError: invalid syntax for the line 217. 
Do you know what could be causing the issue? 

Thank you!

**Comment by brandon-rhodes** [comment]
You could be using a very old copy of Python — what version is your Python interpreter, if you type `python --version`?

**Comment by Milja88** [comment]
I am using python version 3.4 currently.

**Comment by brandon-rhodes** [comment]
With Python 3.4 on my system, that file can be imported without any problem:

```
cd build
python3.4 -c 'import BUILD'
```

So I am at a bit of a loss to understand why exactly the same file would make Python 3.4 happy on my machine, but unhappy on yours. Here is the checksum of exactly my current version of the file if you want to check whether yours has become damaged somehow:

```
$ md5sum BUILD.py
b3e2419222288e5745090c1108341e22  BUILD.py
```

Simply reading the line of code with my eyes, it is perfectly valid Python syntax and Python 3.4 should not have any problems with it — there is no syntax error in the code that I can see.

**Comment by brandon-rhodes** [comment]
Please feel free to re-open this issue if you are able to double-check the checksum on that file so that we can try to discover the syntax error. I hope that you have gotten it fixed by now and are enjoying the tutorial!
